# Generated by Django 4.2.2 on 2023-07-22 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='budget',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='budget.budget'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='budget',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='budget.budget'),
            preserve_default=False,
        ),
    ]
